"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDownToLine, ArrowRight, ArrowUpRight, BookOpen, BookOpenText, Boxes, Check, ChevronDown, ChevronRight, CircleHelp, Clock3, Compass, FileText, FolderOpen, Flower2, Globe2, Layers3, LayoutDashboard, LayoutTemplate, Lightbulb, LoaderCircle, LogOut, Menu, Palette, Plus, Search, Settings2, ShieldCheck, Sparkles, Sprout, WandSparkles, X, type LucideIcon } from "lucide-react";
import { puzzleTemplates, type TemplateKey } from "../../modules/puzzles/templates/catalog";
import type { DashboardData } from "../../modules/dashboard/data";
import { Button } from "../ui/button";
import { Dialog } from "./dialog";
import { AuthForm, BookForm } from "./forms";

const navigation: { label: string; icon: LucideIcon; group: string }[] = [
  { label: "Overview", icon: LayoutDashboard, group: "WORKSPACE" }, { label: "Research", icon: Compass, group: "WORKSPACE" }, { label: "Ideas", icon: Lightbulb, group: "WORKSPACE" },
  { label: "Books", icon: BookOpen, group: "CREATE" }, { label: "Series", icon: Layers3, group: "CREATE" }, { label: "Bundles", icon: Boxes, group: "CREATE" },
  { label: "Templates", icon: LayoutTemplate, group: "LIBRARY" }, { label: "Covers", icon: Palette, group: "LIBRARY" }, { label: "Assets", icon: FolderOpen, group: "LIBRARY" }, { label: "Exports", icon: ArrowDownToLine, group: "LIBRARY" },
];
const ideas = [
  { title: "A little garden. A lot of possibility.", book: "Cottage Garden Word Search", theme: "Gardening", audience: "Seniors", format: "Word search", color: "sage", icon: Sprout, description: "Flowers, herbs, and the quiet joys of gardening. An approachable large-print concept for nature lovers." },
  { title: "Make their next adventure count.", book: "Little Explorer Activity Book", theme: "Nature", audience: "Kids 6–8", format: "Activity book", color: "peach", icon: Compass, description: "A nature-inspired collection of discovery activities. Activity-book generation is planned for a later release." },
  { title: "A passport to everyday words.", book: "Spanish Travel Vocabulary", theme: "Travel", audience: "Language learners", format: "Vocabulary", color: "lavender", icon: Globe2, description: "Useful words for cafés, train stations, and new adventures. Language-learning generation is planned for a later release." },
];
type Modal = "auth" | "book" | "guide" | "activity" | "idea" | "detail" | null;

function BookIllustration() {
  return <div className="book-illustration" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="floating-spark spark-one">✦</span><span className="floating-spark spark-two">✧</span><div className="illustrated-page"><span>FIND YOUR NEXT IDEA</span><div className="letter-grid">{"GARDENFORGEBOOKSCREATEIDEASBLOOMWORDSFLOWERPRINTSTORYPUZZLES".slice(0, 56).split("").map((letter, i) => <b key={i} className={i < 6 ? "highlight-letter" : ""}>{letter}</b>)}</div><span className="page-line" /><span className="page-line short" /></div><div className="illustrated-cover"><span className="cover-eyebrow">THE QUIET COLLECTION</span><span className="cover-title">A little<br />room to<br /><i>bloom.</i></span><div className="cover-flower"><Flower2 strokeWidth={1} size={86} /><Sprout strokeWidth={1} size={65} /></div><span className="cover-bottom">WORD SEARCH & SIMPLE JOYS</span></div><div className="quality-stamp"><ShieldCheck size={18} /><span>Made with intention</span></div></div>;
}

export function Dashboard({ data }: { data: DashboardData }) {
  const router = useRouter();
  const [section, setSection] = useState("Overview");
  const [menu, setMenu] = useState(false);
  const [search, setSearch] = useState("");
  const [modal, setModal] = useState<Modal>(null);
  const [authMode, setAuthMode] = useState<"login" | "register">("register");
  const [idea, setIdea] = useState(ideas[0]!);
  const [selectedBook] = useState<DashboardData["books"][number] | null>(null);
  const [bookTitle, setBookTitle] = useState("");
  const [bookTheme, setBookTheme] = useState("");
  const [bookTemplate, setBookTemplate] = useState<TemplateKey>("word-search");
  const [toast, setToast] = useState("");
  const [signingOut, setSigningOut] = useState(false);
  const [pendingBook, setPendingBook] = useState(false);
  function go(label: string) { setSection(label); setSearch(""); setMenu(false); }
  function newBook(title = "", theme = "", template: TemplateKey = "word-search") { setBookTemplate(template); setBookTitle(title); setBookTheme(theme); setPendingBook(!data.user); setModal(data.user ? "book" : "auth"); }
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 5000); }
  const filteredBooks = data.books.filter(book => book.title.toLowerCase().includes(search.toLowerCase()));
  const filteredIdeas = ideas.filter(item => `${item.title} ${item.book} ${item.theme}`.toLowerCase().includes(search.toLowerCase()));

  function renderBooks() {
    return <div className="panel book-panel"><div className="panel-heading"><div><h2>{section === "Books" ? "Your book library" : "Recent books"}<span className="count-badge">{data.stats.books}</span></h2><p>Good ideas deserve a place on the shelf.</p></div>{section !== "Books" && <button className="text-button" onClick={() => go("Books")}>View library <ArrowRight size={15} /></button>}</div>
      {filteredBooks.length ? <div className="book-list">{filteredBooks.map(book => <button className="book-row" key={book.id} onClick={() => { router.push("/books/" + book.id); }}><div className="mini-book"><BookOpenText size={23} /></div><span><strong>{book.title}</strong><small>{book.type} · {book.pages ? `${book.pages} pages` : "No pages generated"}</small></span><span className="status-badge">{book.status.replaceAll("_", " ").toLowerCase()}</span><ChevronRight size={17} /></button>)}</div> : <div className="empty-books"><div className="empty-book-icon"><BookOpenText size={29} strokeWidth={1.4} /><span><Plus size={12} /></span></div><h3>{search ? "No matching books" : "Your next chapter starts here"}</h3><p>{search ? "Try another title or clear your search." : "Turn a small idea into something worth opening.\nCreate your first book to start building your library."}</p><Button variant="outline" onClick={() => search ? setSearch("") : newBook()}>{search ? "Clear search" : "Create your first book"}{!search && <Plus size={15} />}</Button></div>}
      <div className="panel-footer"><ShieldCheck size={14} /><span>Every book has a place for validation, uniqueness checks, and your final approval.</span></div>
    </div>;
  }

  function renderIdeas() {
    return <section className="inspiration-section"><div className="section-heading"><div><div className="eyebrow"><Sparkles size={13} /> A LITTLE INSPIRATION</div><h2>Big books start with small ideas.</h2></div><span className="editorial-label">Editorial suggestions · not market data</span></div><div className="idea-grid">{filteredIdeas.map(item => <button key={item.book} className={`idea-card ${item.color}`} onClick={() => { setIdea(item); setModal("idea"); }}><div className="idea-top"><item.icon size={27} strokeWidth={1.4} /><span>{item.format}</span><ArrowUpRight size={17} /></div><h3>{item.title}</h3><div className="idea-bottom"><span>{item.theme}</span><span className="dot" /><span>{item.audience}</span></div></button>)}</div>{!filteredIdeas.length && <p className="muted">No matching concepts. Try “garden” or “travel”.</p>}</section>;
  }

  function renderJobs() {
    return <div className="panel jobs-panel"><div className="panel-heading"><h2>Generation activity</h2><button className="icon-button" aria-label="View generation history" onClick={() => setModal("activity")}><ArrowUpRight size={18} /></button></div>{data.jobs.length ? <div className="job-list">{data.jobs.map(job => <div key={job.id}><div><span>{job.type.replaceAll("_", " ").toLowerCase()}</span><strong>{job.progress}%</strong></div><progress value={job.progress} max={100} /><small>{job.status.replaceAll("_", " ")}</small></div>)}</div> : <div className="empty-activity"><span className="activity-icon"><WandSparkles size={23} strokeWidth={1.5} /></span><h3>A little quiet, for now.</h3><p>Your generation progress and recent<br />activity will appear here.</p><span className="idle-label"><span /> No jobs running</span></div>}<div className="cost-row"><span>AI usage this month</span><strong>{data.stats.cost ? `$${data.stats.cost}` : "—"}</strong></div></div>;
  }

  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a>{menu && <button className="sidebar-backdrop" aria-label="Close navigation" onClick={() => setMenu(false)} />}
    <aside className={`sidebar ${menu ? "open" : ""}`}><button className="brand" onClick={() => go("Overview")} aria-label="NicheForge Books home"><span className="brand-icon"><BookOpenText size={24} /></span><span>NicheForge<small>BOOKS</small></span></button>
      <button className="workspace-select" onClick={() => go("Settings")}><span className="workspace-avatar">{data.user?.name.slice(0, 1).toUpperCase() ?? "P"}</span><span><strong>My publishing studio</strong><small>Personal workspace</small></span><ChevronDown size={14} /></button>
      <nav aria-label="Main navigation">{["WORKSPACE", "CREATE", "LIBRARY"].map(group => <div className="nav-group" key={group}><span className="nav-label">{group}</span>{navigation.filter(item => item.group === group).map(item => <button key={item.label} className={`nav-item ${section === item.label ? "active" : ""}`} aria-current={section === item.label ? "page" : undefined} onClick={() => go(item.label)}><item.icon size={18} strokeWidth={1.7} /><span>{item.label}</span>{item.label === "Books" && data.stats.books > 0 && <small>{data.stats.books}</small>}{item.label === "Overview" && section === item.label && <span className="active-dot" />}</button>)}</div>)}</nav>
      <div className="sidebar-bottom"><div className="studio-note"><span><Sprout size={18} /> Built for thoughtful creators.</span><p>Better books. More possibility.</p><button onClick={() => setModal("guide")}>Explore the workflow <ArrowUpRight size={14} /></button></div><button className={`nav-item ${section === "AI Settings" ? "active" : ""}`} onClick={() => go("AI Settings")}><Sparkles size={18} />AI settings</button><button className={`nav-item ${section === "Settings" ? "active" : ""}`} onClick={() => go("Settings")}><Settings2 size={18} />Settings</button><button className="profile" onClick={() => { if (data.user) go("Settings"); else { setAuthMode("login"); setModal("auth"); } }}><span className="profile-avatar">{data.user?.name.slice(0, 2).toUpperCase() ?? "NF"}</span><span><strong>{data.user?.name ?? "Your workspace"}</strong><small>{data.user ? "Personal account" : "Sign in to get started"}</small></span><ChevronRight size={15} /></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button menu-toggle" aria-label="Open navigation" onClick={() => setMenu(true)}><Menu size={21} /></button><span>Workspace</span><ChevronRight size={14} /><strong>{section}</strong></div><div className="topbar-actions"><span className="workspace-status"><span />{data.user ? "Private workspace" : "Workspace preview"}</span><button className="icon-button" aria-label="Publishing guide" onClick={() => setModal("guide")}><CircleHelp size={19} /></button><span className="topbar-divider" /><button className="top-avatar" aria-label={data.user ? "Account settings" : "Sign in"} onClick={() => data.user ? go("Settings") : (setAuthMode("login"), setModal("auth"))}>{data.user?.name.slice(0, 2).toUpperCase() ?? "NF"}</button></div></header>
      <main id="main-content" className="main-content"><div className="page-heading"><div><div className="eyebrow">YOUR PUBLISHING STUDIO</div><h1>{section === "Overview" ? `Room for your next great idea${data.user ? `, ${data.user.name.split(" ")[0]}` : ""}.` : section === "Books" ? "Your growing bookshelf." : section === "Research" ? "Find your next possibility." : section === "Ideas" ? "A spark for your next chapter." : section === "Settings" ? "Make yourself at home." : section === "AI Settings" ? "Intelligence, on your terms." : `${section}, thoughtfully organized.`}</h1><p>{section === "Overview" ? "Discover a niche. Create something unique. Build a library you’re proud of." : "A little structure for the things you want to create."}</p></div><Button onClick={() => newBook()}><Plus size={17} />New book</Button></div>
      {data.error && <div role="alert" className="notice">We couldn’t load your workspace. Your data has not been changed. Check your database connection in Settings.</div>}
      {section === "Overview" && <><section className="hero"><div className="hero-content"><span className="hero-tag"><Sparkles size={13} /> FROM A SMALL SPARK TO A FULL BOOK</span><h2>Your ideas.<br />Their next favorite book.</h2><p>A thoughtful workspace for creating unique puzzle books,<br className="desktop-break" /> activity books, and a little more possibility.</p><div className="hero-actions"><Button onClick={() => newBook()}>Create a book <ArrowRight size={16} /></Button><button className="hero-secondary" onClick={() => go("Research")}>Explore niche ideas <ArrowUpRight size={15} /></button></div><div className="hero-features"><span><Check size={12} /> Your content, organized</span><span><Check size={12} /> Quality at every step</span></div></div><BookIllustration /></section>
      <section className="metrics" aria-label="Library statistics">{[
        { label: "Total books", value: data.stats.books, note: `${data.stats.month} created this month`, icon: BookOpen },
        { label: "Active series", value: data.stats.series, note: "Ideas that belong together", icon: Layers3 },
        { label: "Generated pages", value: data.stats.pages.toLocaleString(), note: "One page at a time", icon: FileText },
        { label: "Avg. uniqueness", value: data.stats.uniqueness === null ? "—" : `${Math.round(data.stats.uniqueness)}%`, note: data.stats.uniqueness === null ? "Awaiting your first validation" : "Measured library comparisons", icon: ShieldCheck },
      ].map(metric => <div key={metric.label} className="metric"><div><span>{metric.label}</span><metric.icon size={17} strokeWidth={1.6} /></div><strong>{metric.value}</strong><small>{metric.note}</small></div>)}</section>
      <div className="workspace-grid">{renderBooks()}{renderJobs()}</div>{renderIdeas()}<section className="workflow-strip"><span className="workflow-icon"><ShieldCheck size={22} strokeWidth={1.5} /></span><div><strong>Designed for quality. Built to be yours.</strong><p>From your first idea to your final approval, every step has a purpose.</p></div><button className="text-button" onClick={() => setModal("guide")}>See the workflow <ArrowRight size={15} /></button></section></>}
      {["Books", "Research", "Ideas"].includes(section) && <><div className="library-toolbar"><label className="search-field"><Search size={17} /><input aria-label={section === "Books" ? "Search books" : "Search ideas"} value={search} onChange={event => setSearch(event.target.value)} placeholder={section === "Books" ? "Search your books…" : "Search inspiration…"} /></label><span className="small muted">{section === "Books" ? `${filteredBooks.length} recent books` : "Curated starting points"}</span></div>{section === "Books" ? renderBooks() : renderIdeas()}{section === "Research" && <div className="notice research-note"><Compass size={20} /><div><strong>Inspiration first. Research next.</strong><p>These are editorial concepts, not verified market opportunities. Keyword demand, competition data, and CSV imports will be added with the research module.</p></div></div>}</>}
      {section === "Templates" && <section aria-label="Reusable puzzle templates"><p className="muted template-intro">Choose a template, set your content and difficulty, and create a fresh book. Every template includes activity pages and checked answer keys.</p><div className="puzzle-template-grid">{puzzleTemplates.map((template, index) => <article className="panel puzzle-template-card" key={template.key}><div className="template-card-top"><span className="template-number">{String(index + 1).padStart(2, "0")}</span><LayoutTemplate size={24} /></div><h2>{template.name}</h2><p>{template.description}</p><small>{template.details}</small><Button variant="outline" onClick={() => newBook("", "", template.key)}>Use template <ArrowRight size={15} /></Button></article>)}</div></section>}
      {["Series", "Bundles", "Covers", "Assets", "Exports"].includes(section) && <div className="panel collection-empty"><span className="collection-icon">{section === "Exports" ? <ArrowDownToLine size={32} /> : section === "Covers" ? <Palette size={32} /> : <Layers3 size={32} />}</span><span className="eyebrow">PART OF YOUR PUBLISHING WORKFLOW</span><h2>{({ Series: "A collection with a common thread.", Bundles: "Good things, better together.", Templates: "Make every page feel considered.", Covers: "Make a memorable first impression.", Assets: "A home for your creative ingredients.", Exports: "The final chapter, ready to share." } as Record<string, string>)[section]}</h2><p>{({ Series: "Series planning will connect related books with consistent branding and a clear reading order.", Bundles: "Bundle building will bring your approved books together in a single product package.", Templates: "Print-friendly layouts for activities, answer keys, and the details in between are coming next.", Covers: "Editable cover templates and print-ready image exports are planned for the cover designer.", Assets: "Your illustrations, images, and generated previews will live here when asset uploads are available.", Exports: "PDF interiors, covers, answer keys, and complete product packages will appear here after validation and approval." } as Record<string, string>)[section]}</p><span className="planned-label">Planned · not available yet</span><Button variant="outline" onClick={() => go("Books")}>Go to your books <ArrowRight size={16} /></Button></div>}
      {section === "AI Settings" && <div className="panel settings-panel"><div className="panel-heading"><div><h2>Your AI providers</h2><p>Choose your tools without changing your workflow.</p></div><span className="planned-label">Connections coming next</span></div>{["OpenAI", "Anthropic Claude", "Google Gemini", "Local models"].map((provider, i) => <div className="provider-row" key={provider}><span className="provider-icon">{["O", "A", "G", "L"][i]}</span><div><strong>{provider}</strong><small>Provider adapter not yet enabled</small></div><span className="neutral-badge">Not connected</span></div>)}<div className="panel-footer"><ShieldCheck size={15} />No API keys are collected or exposed in this interface.</div></div>}
      {section === "Settings" && <div className="settings-grid"><div className="panel settings-panel"><div className="panel-heading"><div><h2>Your account</h2><p>A private home for your publishing projects.</p></div></div><div className="settings-body">{data.user ? <><label className="detail-label">NAME<strong>{data.user.name}</strong></label><label className="detail-label">EMAIL<strong>{data.user.email}</strong></label><Button variant="outline" disabled={signingOut} onClick={async () => { setSigningOut(true); try { const response = await fetch("/api/auth", { method: "DELETE" }); if (!response.ok) throw new Error(); router.refresh(); notify("You’ve been signed out."); } catch { notify("Could not sign out. Please try again."); } finally { setSigningOut(false); } }}>{signingOut ? <LoaderCircle size={16} className="spin" /> : <LogOut size={16} />}Sign out</Button></> : <><p className="muted">Create an account to save drafts and keep your books in one place.</p><Button onClick={() => { setAuthMode("register"); setModal("auth"); }}>Create your account <ArrowRight size={16} /></Button></>}</div></div><div className="panel settings-panel"><div className="panel-heading"><div><h2>Workspace setup</h2><p>Local development connection</p></div></div><div className="settings-body"><span className="neutral-badge">{data.connected ? "Database URL configured" : "Database not configured"}</span><p className="muted small">To save accounts and drafts, configure PostgreSQL in your project’s <code>.env</code> file, then run:</p><pre>npm run db:migrate{"\n"}npm run db:seed</pre><p className="small muted">See README.md for the complete setup. Provider connections and email-based account recovery are not enabled yet.</p></div></div></div>}
      <footer className="workspace-footer"><span><BookOpenText size={13} /> NicheForge Books</span><span>A little more intention. A lot more possibility.</span><button onClick={() => setModal("guide")}>Help & getting started <ArrowUpRight size={12} /></button></footer>
      </main></div>
    {toast && <div role="status" className="toast"><Check size={17} />{toast}<button onClick={() => setToast("")} aria-label="Dismiss notification"><X size={15} /></button></div>}
    {modal && <Dialog title={modal === "auth" ? "Your publishing journey starts here" : modal === "book" ? "Start a new book" : modal === "guide" ? "From idea to bookshelf" : modal === "idea" ? idea.book : modal === "detail" ? selectedBook?.title ?? "Book details" : "Generation history"} close={() => setModal(null)}>
      {modal === "auth" && <AuthForm initialMode={authMode} connected={data.connected} done={() => { setModal(pendingBook ? "book" : null); setPendingBook(false); router.refresh(); notify("Welcome to your publishing studio."); }} />}
      {modal === "book" && <BookForm initialTemplateKey={bookTemplate} initialTitle={bookTitle} initialTheme={bookTheme} done={id => { router.push(`/books/${id}`); }} />}
      {modal === "guide" && <div className="guide-content"><p className="muted">A considered process for making something worth publishing.</p>{[{ title: "Find your spark", text: "Explore the editorial concepts in Research and choose a clear audience." }, { title: "Save your first draft", text: "Create an account, then save a word-search concept with a theme and page count." }, { title: "Create, check, and refine", text: "Coming next: deterministic puzzles, answer keys, page layouts, and uniqueness reports." }, { title: "Give it your final approval", text: "Coming next: review the validated book, approve its revision, and export your product package." }].map((step, i) => <div className="guide-step" key={step.title}><span>{i + 1}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></div>)}<Button onClick={() => { setModal(null); go("Research"); }}>Find an idea <ArrowRight size={16} /></Button></div>}
      {modal === "idea" && <div className="form-stack"><div className={`concept-art ${idea.color}`}><idea.icon size={50} strokeWidth={1.2} /></div><p className="muted">{idea.description}</p><div className="draft-spec"><span>{idea.theme}</span><span>{idea.audience}</span><span>{idea.format}</span></div><p className="small muted">Editorial inspiration only. No marketplace demand or competition has been measured.</p>{idea.format === "Word search" ? <Button onClick={() => newBook(idea.book, idea.theme)}>Use this concept <ArrowRight size={16} /></Button> : <Button variant="outline" onClick={() => newBook("", idea.theme)}>Start a word-search draft <ArrowRight size={16} /></Button>}</div>}
      {modal === "activity" && <div className="form-stack">{data.jobs.length ? data.jobs.map(job => <div key={job.id} className="history-row"><Clock3 size={19} /><div><strong>{job.type.replaceAll("_", " ")}</strong><p>{job.status} · {job.progress}% complete</p></div></div>) : <div className="dialog-empty"><Clock3 size={32} /><h3>No generation jobs yet</h3><p>Drafts do not start generation. Your history will appear here when generation is enabled.</p></div>}<div className="draft-spec"><span>{data.stats.failures} failed validation runs</span></div></div>}
      {modal === "detail" && selectedBook && <div className="form-stack"><span className="status-badge">{selectedBook.status.toLowerCase()}</span><p className="muted">Your concept is safely saved. The page editor and puzzle generation workflow will be available in a later phase.</p><div className="draft-spec"><span>{selectedBook.type}</span><span>{selectedBook.pages} generated pages</span><span>Created {new Date(selectedBook.createdAt).toLocaleDateString()}</span></div><Button variant="outline" onClick={() => setModal(null)}>Back to library</Button></div>}
    </Dialog>}
  </div>;
}
